/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Activity {
  'id' : EntityId,
  'direction' : string,
  'activityType' : string,
  'approvedAt' : [] | [Timestamp],
  'approvedBy' : [] | [string],
  'createdAt' : Timestamp,
  'createdBy' : string,
  'entityId' : EntityId,
  'notes' : string,
  'requiresApproval' : boolean,
  'entityType' : EntityType,
}
export interface ApprovalItem {
  'id' : EntityId,
  'status' : string,
  'approvedAt' : [] | [Timestamp],
  'approvedBy' : [] | [string],
  'description' : string,
  'entityId' : EntityId,
  'snoozedUntil' : [] | [Timestamp],
  'notes' : [] | [string],
  'itemType' : string,
  'details' : string,
  'entityName' : string,
  'entityType' : EntityType,
  'requestedAt' : Timestamp,
  'requestedBy' : string,
}
export interface BenchMatch {
  'id' : bigint,
  'rate' : number,
  'role' : string,
  'importedAt' : Timestamp,
  'matchScore' : number,
  'experience' : string,
  'skill' : string,
  'candidateName' : string,
  'vendorName' : string,
}
export interface BenchRecord {
  'id' : bigint,
  'rate' : number,
  'role' : string,
  'importedAt' : Timestamp,
  'experience' : string,
  'skill' : string,
  'candidateName' : string,
  'vendorName' : string,
}
export interface BenchRecordInput {
  'rate' : number,
  'role' : string,
  'experience' : string,
  'skill' : string,
  'candidateName' : string,
  'vendorName' : string,
}
export interface Candidate {
  'id' : EntityId,
  'placementProbability' : bigint,
  'source' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'salaryExpectation' : number,
  'email' : string,
  'experience' : string,
  'availability' : string,
  'pipelineStage' : string,
  'daysInStage' : bigint,
  'healthScore' : bigint,
  'phone' : string,
  'lastActivityAt' : Timestamp,
  'lastContact' : Timestamp,
  'skills' : string,
}
export interface Client {
  'id' : EntityId,
  'hiringManager' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'email' : string,
  'company' : string,
  'pipelineStage' : string,
  'notes' : string,
  'healthScore' : bigint,
  'phone' : string,
  'lastActivityAt' : Timestamp,
  'budget' : number,
  'churnRisk' : string,
  'timeline' : string,
}
export type EntityId = string;
export type EntityType = { 'client' : null } |
  { 'vendor' : null } |
  { 'recruiter' : null } |
  { 'candidate' : null };
export interface FollowUp {
  'id' : EntityId,
  'status' : string,
  'triggerReason' : string,
  'approvedAt' : [] | [Timestamp],
  'approvedBy' : [] | [string],
  'createdAt' : Timestamp,
  'suggestedAction' : string,
  'sentAt' : [] | [Timestamp],
  'entityId' : EntityId,
  'snoozedUntil' : [] | [Timestamp],
  'entityType' : EntityType,
  'suggestedMessage' : string,
}
export type HealthStatus = { 'red' : null } |
  { 'green' : null } |
  { 'yellow' : null };
export interface Job {
  'id' : EntityId,
  'status' : string,
  'title' : string,
  'clientId' : EntityId,
  'createdAt' : Timestamp,
  'rateMax' : number,
  'rateMin' : number,
  'filledAt' : [] | [Timestamp],
  'requirements' : string,
}
export interface MorningBriefing {
  'clientInterviewsToday' : bigint,
  'staleCandidates' : bigint,
  'recruiterSummaries' : Array<RecruiterSummary>,
  'vendorFollowUps' : bigint,
  'pendingApprovals' : bigint,
  'date' : string,
  'generatedAt' : Timestamp,
  'aiSuggestions' : Array<string>,
  'pendingOfferApprovals' : bigint,
}
export interface PipelineHistoryEntry {
  'changedAt' : bigint,
  'changedBy' : string,
  'fromStage' : string,
  'toStage' : string,
}
export interface PipelineStage {
  'stageOrder' : bigint,
  'requiresApproval' : boolean,
  'entityType' : EntityType,
  'slaHours' : bigint,
  'stageName' : string,
}
export interface PulseDashboard {
  'generatedAt' : Timestamp,
  'rows' : Array<PulseRow>,
}
export interface PulseRow {
  'healthStatus' : HealthStatus,
  'pipelineStage' : string,
  'entityId' : EntityId,
  'actionNeeded' : string,
  'entityName' : string,
  'entityType' : EntityType,
  'healthScore' : bigint,
  'lastActivityAt' : Timestamp,
}
export interface Recruiter {
  'id' : EntityId,
  'productivityScore' : bigint,
  'emailsToday' : bigint,
  'name' : string,
  'createdAt' : Timestamp,
  'tasksCompleted' : bigint,
  'email' : string,
  'interviewsScheduled' : bigint,
  'pipelineStage' : string,
  'callsToday' : bigint,
  'healthScore' : bigint,
  'phone' : string,
  'lastActivityAt' : Timestamp,
  'submissionsToday' : bigint,
}
export interface RecruiterMetrics {
  'id' : EntityId,
  'emailsSent' : bigint,
  'productivityScore' : bigint,
  'date' : string,
  'recruiterId' : EntityId,
  'tasksCompleted' : bigint,
  'callsMade' : bigint,
  'submissions' : bigint,
  'interviewsScheduled' : bigint,
  'notes' : string,
}
export interface RecruiterSummary {
  'productivityScore' : bigint,
  'name' : string,
  'recruiterId' : EntityId,
  'callsToday' : bigint,
  'submissionsToday' : bigint,
  'flagged' : boolean,
}
export interface Resume {
  'id' : EntityId,
  'rawText' : string,
  'sourceVendorId' : [] | [EntityId],
  'yearsExperience' : [] | [bigint],
  'createdAt' : Timestamp,
  'fileName' : string,
  'extractedRole' : string,
  'email' : [] | [string],
  'extractedSkills' : Array<string>,
  'extractedExperience' : string,
  'candidateName' : string,
  'phone' : [] | [string],
  'location' : [] | [string],
  'fileUrl' : string,
}
export interface ResumeInput {
  'rawText' : string,
  'sourceVendorId' : [] | [EntityId],
  'yearsExperience' : [] | [bigint],
  'fileName' : string,
  'extractedRole' : string,
  'email' : [] | [string],
  'extractedSkills' : Array<string>,
  'extractedExperience' : string,
  'candidateName' : string,
  'phone' : [] | [string],
  'location' : [] | [string],
  'fileUrl' : string,
}
export interface ResumeJobMatch {
  'availScore' : number,
  'jobId' : EntityId,
  'matchScore' : number,
  'skillsScore' : number,
  'jobTitle' : string,
  'rateScore' : number,
  'expScore' : number,
}
export interface Submission {
  'id' : EntityId,
  'rateProposed' : number,
  'pipelineHistory' : Array<PipelineHistoryEntry>,
  'approvedAt' : [] | [Timestamp],
  'approvedBy' : [] | [string],
  'jobId' : EntityId,
  'submittedAt' : Timestamp,
  'submittedBy' : string,
  'resumeId' : [] | [EntityId],
  'pipelineStage' : SubmissionPipelineStage,
  'vendorId' : [] | [EntityId],
  'notes' : [] | [string],
  'candidateId' : EntityId,
}
export interface SubmissionInput {
  'rateProposed' : number,
  'jobId' : EntityId,
  'submittedBy' : string,
  'resumeId' : [] | [EntityId],
  'vendorId' : [] | [EntityId],
  'notes' : [] | [string],
  'candidateId' : EntityId,
}
export type SubmissionPipelineStage = string;
export type Timestamp = bigint;
export interface Vendor {
  'id' : EntityId,
  'status' : string,
  'contactName' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'rateMax' : number,
  'rateMin' : number,
  'submissionsAccepted' : bigint,
  'submissions' : bigint,
  'email' : string,
  'specialty' : string,
  'qualityScore' : number,
  'company' : string,
  'pipelineStage' : string,
  'notes' : string,
  'healthScore' : bigint,
  'responseTimeHours' : number,
  'phone' : string,
  'lastActivityAt' : Timestamp,
}
export interface VendorMetrics {
  'id' : EntityId,
  'date' : string,
  'placements' : bigint,
  'submissionsAccepted' : bigint,
  'submissions' : bigint,
  'interviewsScheduled' : bigint,
  'qualityScore' : number,
  'vendorId' : EntityId,
  'responseTimeHours' : number,
}
export interface _SERVICE {
  'approveItem' : ActorMethod<[string, string], boolean>,
  'createApprovalItem' : ActorMethod<
    [string, string, EntityType, string, string, string, string],
    ApprovalItem
  >,
  'createCandidate' : ActorMethod<
    [string, string, string, string, string, string, number, string],
    Candidate
  >,
  'createClient' : ActorMethod<
    [string, string, string, string, string, number, string, string],
    Client
  >,
  'createFollowUp' : ActorMethod<
    [string, EntityType, string, string, string],
    FollowUp
  >,
  'createJob' : ActorMethod<[string, string, string, number, number], Job>,
  'createRecruiter' : ActorMethod<[string, string, string], Recruiter>,
  'createResume' : ActorMethod<[ResumeInput], Resume>,
  'createSubmission' : ActorMethod<[SubmissionInput], Submission>,
  'createVendor' : ActorMethod<
    [string, string, string, string, string, string, number, number, string],
    Vendor
  >,
  'deleteBenchRecord' : ActorMethod<
    [bigint],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'deleteCandidate' : ActorMethod<[string], boolean>,
  'deleteClient' : ActorMethod<[string], boolean>,
  'deleteRecruiter' : ActorMethod<[string], boolean>,
  'deleteResume' : ActorMethod<[string], boolean>,
  'deleteSubmission' : ActorMethod<[string], boolean>,
  'deleteVendor' : ActorMethod<[string], boolean>,
  'getActivitiesForEntity' : ActorMethod<[string], Array<Activity>>,
  'getAllActivities' : ActorMethod<[], Array<Activity>>,
  'getCandidate' : ActorMethod<[string], [] | [Candidate]>,
  'getClient' : ActorMethod<[string], [] | [Client]>,
  'getJob' : ActorMethod<[string], [] | [Job]>,
  'getMorningBriefing' : ActorMethod<[], MorningBriefing>,
  'getPipelineStages' : ActorMethod<[EntityType], Array<PipelineStage>>,
  'getPulseDashboard' : ActorMethod<[], PulseDashboard>,
  'getRecruiter' : ActorMethod<[string], [] | [Recruiter]>,
  'getRecruiterMetrics' : ActorMethod<
    [string, string],
    [] | [RecruiterMetrics]
  >,
  'getRecruiterMetricsHistory' : ActorMethod<[string], Array<RecruiterMetrics>>,
  'getResume' : ActorMethod<[string], [] | [Resume]>,
  'getSubmission' : ActorMethod<[string], [] | [Submission]>,
  'getVendor' : ActorMethod<[string], [] | [Vendor]>,
  'getVendorMetrics' : ActorMethod<[string, string], [] | [VendorMetrics]>,
  'listApprovalHistory' : ActorMethod<[], Array<ApprovalItem>>,
  'listBench' : ActorMethod<
    [[] | [string], [] | [string], [] | [string]],
    Array<BenchRecord>
  >,
  'listCandidates' : ActorMethod<[], Array<Candidate>>,
  'listClients' : ActorMethod<[], Array<Client>>,
  'listFollowUps' : ActorMethod<[], Array<FollowUp>>,
  'listJobs' : ActorMethod<[], Array<Job>>,
  'listJobsForClient' : ActorMethod<[string], Array<Job>>,
  'listPendingApprovals' : ActorMethod<[], Array<ApprovalItem>>,
  'listPendingFollowUps' : ActorMethod<[], Array<FollowUp>>,
  'listRecruiters' : ActorMethod<[], Array<Recruiter>>,
  'listResumes' : ActorMethod<[], Array<Resume>>,
  'listSubmissions' : ActorMethod<[], Array<Submission>>,
  'listSubmissionsForCandidate' : ActorMethod<[string], Array<Submission>>,
  'listSubmissionsForJob' : ActorMethod<[string], Array<Submission>>,
  'listSubmissionsForResume' : ActorMethod<[string], Array<Submission>>,
  'listVendors' : ActorMethod<[], Array<Vendor>>,
  'logActivity' : ActorMethod<
    [string, EntityType, string, string, string, string, boolean],
    Activity
  >,
  'logRecruiterMetrics' : ActorMethod<
    [string, string, bigint, bigint, bigint, bigint, bigint, bigint, string],
    RecruiterMetrics
  >,
  'logVendorMetrics' : ActorMethod<
    [string, string, bigint, bigint, bigint, bigint, number, number],
    VendorMetrics
  >,
  'matchBench' : ActorMethod<[string], Array<BenchMatch>>,
  'matchResumeToJobs' : ActorMethod<[string], Array<ResumeJobMatch>>,
  'rejectItem' : ActorMethod<[string, string, string], boolean>,
  'runFollowUpEngine' : ActorMethod<[], bigint>,
  'seedSampleData' : ActorMethod<[], string>,
  'snoozeItem' : ActorMethod<[string, bigint], boolean>,
  'updateApprovalItem' : ActorMethod<[ApprovalItem], boolean>,
  'updateCandidate' : ActorMethod<[Candidate], boolean>,
  'updateClient' : ActorMethod<[Client], boolean>,
  'updateEntityStage' : ActorMethod<
    [string, EntityType, string, string],
    { 'ok' : null } |
      { 'requiresApproval' : string }
  >,
  'updateFollowUpStatus' : ActorMethod<
    [string, string, [] | [string], [] | [bigint]],
    boolean
  >,
  'updateJob' : ActorMethod<[Job], boolean>,
  'updateRecruiter' : ActorMethod<[Recruiter], boolean>,
  'updateResume' : ActorMethod<[string, ResumeInput], boolean>,
  'updateSubmission' : ActorMethod<[Submission], boolean>,
  'updateSubmissionStage' : ActorMethod<[string, string, string], boolean>,
  'updateVendor' : ActorMethod<[Vendor], boolean>,
  'uploadBenchRecords' : ActorMethod<
    [Array<BenchRecordInput>],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];