/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface Recruiter {
    id: EntityId;
    productivityScore: bigint;
    emailsToday: bigint;
    name: string;
    createdAt: Timestamp;
    tasksCompleted: bigint;
    email: string;
    interviewsScheduled: bigint;
    pipelineStage: string;
    callsToday: bigint;
    healthScore: bigint;
    phone: string;
    lastActivityAt: Timestamp;
    submissionsToday: bigint;
}
export type EntityId = string;
export interface RecruiterMetrics {
    id: EntityId;
    emailsSent: bigint;
    productivityScore: bigint;
    date: string;
    recruiterId: EntityId;
    tasksCompleted: bigint;
    callsMade: bigint;
    submissions: bigint;
    interviewsScheduled: bigint;
    notes: string;
}
export interface RecruiterSummary {
    productivityScore: bigint;
    name: string;
    recruiterId: EntityId;
    callsToday: bigint;
    submissionsToday: bigint;
    flagged: boolean;
}
export interface ResumeInput {
    rawText: string;
    sourceVendorId?: EntityId;
    yearsExperience?: bigint;
    fileName: string;
    extractedRole: string;
    email?: string;
    extractedSkills: Array<string>;
    extractedExperience: string;
    candidateName: string;
    phone?: string;
    location?: string;
    fileUrl: string;
}
export interface PulseDashboard {
    generatedAt: Timestamp;
    rows: Array<PulseRow>;
}
export interface BenchRecord {
    id: bigint;
    rate: number;
    role: string;
    importedAt: Timestamp;
    experience: string;
    skill: string;
    candidateName: string;
    vendorName: string;
}
export interface Job {
    id: EntityId;
    status: string;
    title: string;
    clientId: EntityId;
    createdAt: Timestamp;
    rateMax: number;
    rateMin: number;
    filledAt?: Timestamp;
    requirements: string;
}
export interface SubmissionInput {
    rateProposed: number;
    jobId: EntityId;
    submittedBy: string;
    resumeId?: EntityId;
    vendorId?: EntityId;
    notes?: string;
    candidateId: EntityId;
}
export interface PipelineStage {
    stageOrder: bigint;
    requiresApproval: boolean;
    entityType: EntityType;
    slaHours: bigint;
    stageName: string;
}
export type SubmissionPipelineStage = string;
export interface Resume {
    id: EntityId;
    rawText: string;
    sourceVendorId?: EntityId;
    yearsExperience?: bigint;
    createdAt: Timestamp;
    fileName: string;
    extractedRole: string;
    email?: string;
    extractedSkills: Array<string>;
    extractedExperience: string;
    candidateName: string;
    phone?: string;
    location?: string;
    fileUrl: string;
}
export interface BenchMatch {
    id: bigint;
    rate: number;
    role: string;
    importedAt: Timestamp;
    matchScore: number;
    experience: string;
    skill: string;
    candidateName: string;
    vendorName: string;
}
export interface Vendor {
    id: EntityId;
    status: string;
    contactName: string;
    name: string;
    createdAt: Timestamp;
    rateMax: number;
    rateMin: number;
    submissionsAccepted: bigint;
    submissions: bigint;
    email: string;
    specialty: string;
    qualityScore: number;
    company: string;
    pipelineStage: string;
    notes: string;
    healthScore: bigint;
    responseTimeHours: number;
    phone: string;
    lastActivityAt: Timestamp;
}
export interface Submission {
    id: EntityId;
    rateProposed: number;
    pipelineHistory: Array<PipelineHistoryEntry>;
    approvedAt?: Timestamp;
    approvedBy?: string;
    jobId: EntityId;
    submittedAt: Timestamp;
    submittedBy: string;
    resumeId?: EntityId;
    pipelineStage: SubmissionPipelineStage;
    vendorId?: EntityId;
    notes?: string;
    candidateId: EntityId;
}
export interface Client {
    id: EntityId;
    hiringManager: string;
    name: string;
    createdAt: Timestamp;
    email: string;
    company: string;
    pipelineStage: string;
    notes: string;
    healthScore: bigint;
    phone: string;
    lastActivityAt: Timestamp;
    budget: number;
    churnRisk: string;
    timeline: string;
}
export interface Candidate {
    id: EntityId;
    placementProbability: bigint;
    source: string;
    name: string;
    createdAt: Timestamp;
    salaryExpectation: number;
    email: string;
    experience: string;
    availability: string;
    pipelineStage: string;
    daysInStage: bigint;
    healthScore: bigint;
    phone: string;
    lastActivityAt: Timestamp;
    lastContact: Timestamp;
    skills: string;
}
export interface PulseRow {
    healthStatus: HealthStatus;
    pipelineStage: string;
    entityId: EntityId;
    actionNeeded: string;
    entityName: string;
    entityType: EntityType;
    healthScore: bigint;
    lastActivityAt: Timestamp;
}
export interface MorningBriefing {
    clientInterviewsToday: bigint;
    staleCandidates: bigint;
    recruiterSummaries: Array<RecruiterSummary>;
    vendorFollowUps: bigint;
    pendingApprovals: bigint;
    date: string;
    generatedAt: Timestamp;
    aiSuggestions: Array<string>;
    pendingOfferApprovals: bigint;
}
export interface BenchRecordInput {
    rate: number;
    role: string;
    experience: string;
    skill: string;
    candidateName: string;
    vendorName: string;
}
export interface VendorMetrics {
    id: EntityId;
    date: string;
    placements: bigint;
    submissionsAccepted: bigint;
    submissions: bigint;
    interviewsScheduled: bigint;
    qualityScore: number;
    vendorId: EntityId;
    responseTimeHours: number;
}
export interface PipelineHistoryEntry {
    changedAt: bigint;
    changedBy: string;
    fromStage: string;
    toStage: string;
}
export interface Activity {
    id: EntityId;
    direction: string;
    activityType: string;
    approvedAt?: Timestamp;
    approvedBy?: string;
    createdAt: Timestamp;
    createdBy: string;
    entityId: EntityId;
    notes: string;
    requiresApproval: boolean;
    entityType: EntityType;
}
export interface FollowUp {
    id: EntityId;
    status: string;
    triggerReason: string;
    approvedAt?: Timestamp;
    approvedBy?: string;
    createdAt: Timestamp;
    suggestedAction: string;
    sentAt?: Timestamp;
    entityId: EntityId;
    snoozedUntil?: Timestamp;
    entityType: EntityType;
    suggestedMessage: string;
}
export interface ApprovalItem {
    id: EntityId;
    status: string;
    approvedAt?: Timestamp;
    approvedBy?: string;
    description: string;
    entityId: EntityId;
    snoozedUntil?: Timestamp;
    notes?: string;
    itemType: string;
    details: string;
    entityName: string;
    entityType: EntityType;
    requestedAt: Timestamp;
    requestedBy: string;
}
export interface ResumeJobMatch {
    availScore: number;
    jobId: EntityId;
    matchScore: number;
    skillsScore: number;
    jobTitle: string;
    rateScore: number;
    expScore: number;
}
export enum EntityType {
    client = "client",
    vendor = "vendor",
    recruiter = "recruiter",
    candidate = "candidate"
}
export enum HealthStatus {
    red = "red",
    green = "green",
    yellow = "yellow"
}
export interface backendInterface {
    approveItem(id: string, approvedBy: string): Promise<boolean>;
    createApprovalItem(itemType: string, entityId: string, entityType: EntityType, entityName: string, description: string, details: string, requestedBy: string): Promise<ApprovalItem>;
    createCandidate(name: string, email: string, phone: string, skills: string, experience: string, source: string, salaryExpectation: number, availability: string): Promise<Candidate>;
    createClient(name: string, company: string, hiringManager: string, email: string, phone: string, budget: number, timeline: string, notes: string): Promise<Client>;
    createFollowUp(entityId: string, entityType: EntityType, triggerReason: string, suggestedAction: string, suggestedMessage: string): Promise<FollowUp>;
    createJob(clientId: string, title: string, requirements: string, rateMin: number, rateMax: number): Promise<Job>;
    createRecruiter(name: string, email: string, phone: string): Promise<Recruiter>;
    createResume(input: ResumeInput): Promise<Resume>;
    createSubmission(input: SubmissionInput): Promise<Submission>;
    createVendor(name: string, company: string, contactName: string, email: string, phone: string, specialty: string, rateMin: number, rateMax: number, notes: string): Promise<Vendor>;
    deleteBenchRecord(id: bigint): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteCandidate(id: string): Promise<boolean>;
    deleteClient(id: string): Promise<boolean>;
    deleteRecruiter(id: string): Promise<boolean>;
    deleteResume(id: string): Promise<boolean>;
    deleteSubmission(id: string): Promise<boolean>;
    deleteVendor(id: string): Promise<boolean>;
    getActivitiesForEntity(entityId: string): Promise<Array<Activity>>;
    getAllActivities(): Promise<Array<Activity>>;
    getCandidate(id: string): Promise<Candidate | null>;
    getClient(id: string): Promise<Client | null>;
    getJob(id: string): Promise<Job | null>;
    getMorningBriefing(): Promise<MorningBriefing>;
    getPipelineStages(entityType: EntityType): Promise<Array<PipelineStage>>;
    getPulseDashboard(): Promise<PulseDashboard>;
    getRecruiter(id: string): Promise<Recruiter | null>;
    getRecruiterMetrics(recruiterId: string, date: string): Promise<RecruiterMetrics | null>;
    getRecruiterMetricsHistory(recruiterId: string): Promise<Array<RecruiterMetrics>>;
    getResume(id: string): Promise<Resume | null>;
    getSubmission(id: string): Promise<Submission | null>;
    getVendor(id: string): Promise<Vendor | null>;
    getVendorMetrics(vendorId: string, date: string): Promise<VendorMetrics | null>;
    listApprovalHistory(): Promise<Array<ApprovalItem>>;
    listBench(vendorFilter: string | null, roleFilter: string | null, skillFilter: string | null): Promise<Array<BenchRecord>>;
    listCandidates(): Promise<Array<Candidate>>;
    listClients(): Promise<Array<Client>>;
    listFollowUps(): Promise<Array<FollowUp>>;
    listJobs(): Promise<Array<Job>>;
    listJobsForClient(clientId: string): Promise<Array<Job>>;
    listPendingApprovals(): Promise<Array<ApprovalItem>>;
    listPendingFollowUps(): Promise<Array<FollowUp>>;
    listRecruiters(): Promise<Array<Recruiter>>;
    listResumes(): Promise<Array<Resume>>;
    listSubmissions(): Promise<Array<Submission>>;
    listSubmissionsForCandidate(candidateId: string): Promise<Array<Submission>>;
    listSubmissionsForJob(jobId: string): Promise<Array<Submission>>;
    listSubmissionsForResume(resumeId: string): Promise<Array<Submission>>;
    listVendors(): Promise<Array<Vendor>>;
    logActivity(entityId: string, entityType: EntityType, activityType: string, direction: string, notes: string, createdBy: string, requiresApproval: boolean): Promise<Activity>;
    logRecruiterMetrics(recruiterId: string, date: string, callsMade: bigint, emailsSent: bigint, submissions: bigint, interviewsScheduled: bigint, tasksCompleted: bigint, productivityScore: bigint, notes: string): Promise<RecruiterMetrics>;
    logVendorMetrics(vendorId: string, date: string, submissions: bigint, submissionsAccepted: bigint, interviewsScheduled: bigint, placements: bigint, responseTimeHours: number, qualityScore: number): Promise<VendorMetrics>;
    matchBench(jobId: string): Promise<Array<BenchMatch>>;
    matchResumeToJobs(resumeId: string): Promise<Array<ResumeJobMatch>>;
    rejectItem(id: string, rejectedBy: string, notes: string): Promise<boolean>;
    runFollowUpEngine(): Promise<bigint>;
    seedSampleData(): Promise<string>;
    snoozeItem(id: string, snoozedUntil: bigint): Promise<boolean>;
    updateApprovalItem(updated: ApprovalItem): Promise<boolean>;
    updateCandidate(updated: Candidate): Promise<boolean>;
    updateClient(updated: Client): Promise<boolean>;
    updateEntityStage(entityId: string, entityType: EntityType, newStage: string, requestedBy: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "requiresApproval";
        requiresApproval: string;
    }>;
    updateFollowUpStatus(id: string, status: string, approvedBy: string | null, snoozedUntil: bigint | null): Promise<boolean>;
    updateJob(updated: Job): Promise<boolean>;
    updateRecruiter(updated: Recruiter): Promise<boolean>;
    updateResume(id: string, input: ResumeInput): Promise<boolean>;
    updateSubmission(updated: Submission): Promise<boolean>;
    updateSubmissionStage(id: string, newStage: string, changedBy: string): Promise<boolean>;
    updateVendor(updated: Vendor): Promise<boolean>;
    uploadBenchRecords(records: Array<BenchRecordInput>): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: string;
    }>;
}
import type { Activity as _Activity, ApprovalItem as _ApprovalItem, Candidate as _Candidate, Client as _Client, EntityId as _EntityId, EntityType as _EntityType, FollowUp as _FollowUp, HealthStatus as _HealthStatus, Job as _Job, PipelineHistoryEntry as _PipelineHistoryEntry, PipelineStage as _PipelineStage, PulseDashboard as _PulseDashboard, PulseRow as _PulseRow, Recruiter as _Recruiter, RecruiterMetrics as _RecruiterMetrics, Resume as _Resume, ResumeInput as _ResumeInput, Submission as _Submission, SubmissionInput as _SubmissionInput, SubmissionPipelineStage as _SubmissionPipelineStage, Timestamp as _Timestamp, Vendor as _Vendor, VendorMetrics as _VendorMetrics } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async approveItem(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.approveItem(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveItem(arg0, arg1);
            return result;
        }
    }
    async createApprovalItem(arg0: string, arg1: string, arg2: EntityType, arg3: string, arg4: string, arg5: string, arg6: string): Promise<ApprovalItem> {
        if (this.processError) {
            try {
                const result = await this.actor.createApprovalItem(arg0, arg1, to_candid_EntityType_n1(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6);
                return from_candid_ApprovalItem_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createApprovalItem(arg0, arg1, to_candid_EntityType_n1(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6);
            return from_candid_ApprovalItem_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async createCandidate(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: number, arg7: string): Promise<Candidate> {
        if (this.processError) {
            try {
                const result = await this.actor.createCandidate(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCandidate(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async createClient(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: number, arg6: string, arg7: string): Promise<Client> {
        if (this.processError) {
            try {
                const result = await this.actor.createClient(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createClient(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async createFollowUp(arg0: string, arg1: EntityType, arg2: string, arg3: string, arg4: string): Promise<FollowUp> {
        if (this.processError) {
            try {
                const result = await this.actor.createFollowUp(arg0, to_candid_EntityType_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
                return from_candid_FollowUp_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFollowUp(arg0, to_candid_EntityType_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
            return from_candid_FollowUp_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async createJob(arg0: string, arg1: string, arg2: string, arg3: number, arg4: number): Promise<Job> {
        if (this.processError) {
            try {
                const result = await this.actor.createJob(arg0, arg1, arg2, arg3, arg4);
                return from_candid_Job_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createJob(arg0, arg1, arg2, arg3, arg4);
            return from_candid_Job_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async createRecruiter(arg0: string, arg1: string, arg2: string): Promise<Recruiter> {
        if (this.processError) {
            try {
                const result = await this.actor.createRecruiter(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRecruiter(arg0, arg1, arg2);
            return result;
        }
    }
    async createResume(arg0: ResumeInput): Promise<Resume> {
        if (this.processError) {
            try {
                const result = await this.actor.createResume(to_candid_ResumeInput_n13(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Resume_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createResume(to_candid_ResumeInput_n13(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Resume_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async createSubmission(arg0: SubmissionInput): Promise<Submission> {
        if (this.processError) {
            try {
                const result = await this.actor.createSubmission(to_candid_SubmissionInput_n19(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Submission_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSubmission(to_candid_SubmissionInput_n19(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Submission_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async createVendor(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: number, arg7: number, arg8: string): Promise<Vendor> {
        if (this.processError) {
            try {
                const result = await this.actor.createVendor(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createVendor(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async deleteBenchRecord(arg0: bigint): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBenchRecord(arg0);
                return from_candid_variant_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBenchRecord(arg0);
            return from_candid_variant_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteCandidate(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCandidate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCandidate(arg0);
            return result;
        }
    }
    async deleteClient(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteClient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteClient(arg0);
            return result;
        }
    }
    async deleteRecruiter(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRecruiter(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRecruiter(arg0);
            return result;
        }
    }
    async deleteResume(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteResume(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteResume(arg0);
            return result;
        }
    }
    async deleteSubmission(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSubmission(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSubmission(arg0);
            return result;
        }
    }
    async deleteVendor(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVendor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVendor(arg0);
            return result;
        }
    }
    async getActivitiesForEntity(arg0: string): Promise<Array<Activity>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivitiesForEntity(arg0);
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivitiesForEntity(arg0);
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllActivities(): Promise<Array<Activity>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllActivities();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllActivities();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCandidate(arg0: string): Promise<Candidate | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCandidate(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCandidate(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClient(arg0: string): Promise<Client | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getClient(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClient(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJob(arg0: string): Promise<Job | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getJob(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJob(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMorningBriefing(): Promise<MorningBriefing> {
        if (this.processError) {
            try {
                const result = await this.actor.getMorningBriefing();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMorningBriefing();
            return result;
        }
    }
    async getPipelineStages(arg0: EntityType): Promise<Array<PipelineStage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPipelineStages(to_candid_EntityType_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPipelineStages(to_candid_EntityType_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPulseDashboard(): Promise<PulseDashboard> {
        if (this.processError) {
            try {
                const result = await this.actor.getPulseDashboard();
                return from_candid_PulseDashboard_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPulseDashboard();
            return from_candid_PulseDashboard_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecruiter(arg0: string): Promise<Recruiter | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecruiter(arg0);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecruiter(arg0);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecruiterMetrics(arg0: string, arg1: string): Promise<RecruiterMetrics | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecruiterMetrics(arg0, arg1);
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecruiterMetrics(arg0, arg1);
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecruiterMetricsHistory(arg0: string): Promise<Array<RecruiterMetrics>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecruiterMetricsHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecruiterMetricsHistory(arg0);
            return result;
        }
    }
    async getResume(arg0: string): Promise<Resume | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getResume(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResume(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSubmission(arg0: string): Promise<Submission | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubmission(arg0);
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubmission(arg0);
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVendor(arg0: string): Promise<Vendor | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVendor(arg0);
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVendor(arg0);
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVendorMetrics(arg0: string, arg1: string): Promise<VendorMetrics | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVendorMetrics(arg0, arg1);
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVendorMetrics(arg0, arg1);
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async listApprovalHistory(): Promise<Array<ApprovalItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovalHistory();
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovalHistory();
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async listBench(arg0: string | null, arg1: string | null, arg2: string | null): Promise<Array<BenchRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.listBench(to_candid_opt_n47(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n47(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n47(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listBench(to_candid_opt_n47(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n47(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n47(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async listCandidates(): Promise<Array<Candidate>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCandidates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCandidates();
            return result;
        }
    }
    async listClients(): Promise<Array<Client>> {
        if (this.processError) {
            try {
                const result = await this.actor.listClients();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listClients();
            return result;
        }
    }
    async listFollowUps(): Promise<Array<FollowUp>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFollowUps();
                return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFollowUps();
            return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async listJobs(): Promise<Array<Job>> {
        if (this.processError) {
            try {
                const result = await this.actor.listJobs();
                return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listJobs();
            return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async listJobsForClient(arg0: string): Promise<Array<Job>> {
        if (this.processError) {
            try {
                const result = await this.actor.listJobsForClient(arg0);
                return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listJobsForClient(arg0);
            return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPendingApprovals(): Promise<Array<ApprovalItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPendingApprovals();
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPendingApprovals();
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPendingFollowUps(): Promise<Array<FollowUp>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPendingFollowUps();
                return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPendingFollowUps();
            return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async listRecruiters(): Promise<Array<Recruiter>> {
        if (this.processError) {
            try {
                const result = await this.actor.listRecruiters();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listRecruiters();
            return result;
        }
    }
    async listResumes(): Promise<Array<Resume>> {
        if (this.processError) {
            try {
                const result = await this.actor.listResumes();
                return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listResumes();
            return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async listSubmissions(): Promise<Array<Submission>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSubmissions();
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSubmissions();
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async listSubmissionsForCandidate(arg0: string): Promise<Array<Submission>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSubmissionsForCandidate(arg0);
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSubmissionsForCandidate(arg0);
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async listSubmissionsForJob(arg0: string): Promise<Array<Submission>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSubmissionsForJob(arg0);
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSubmissionsForJob(arg0);
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async listSubmissionsForResume(arg0: string): Promise<Array<Submission>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSubmissionsForResume(arg0);
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSubmissionsForResume(arg0);
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async listVendors(): Promise<Array<Vendor>> {
        if (this.processError) {
            try {
                const result = await this.actor.listVendors();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listVendors();
            return result;
        }
    }
    async logActivity(arg0: string, arg1: EntityType, arg2: string, arg3: string, arg4: string, arg5: string, arg6: boolean): Promise<Activity> {
        if (this.processError) {
            try {
                const result = await this.actor.logActivity(arg0, to_candid_EntityType_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6);
                return from_candid_Activity_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logActivity(arg0, to_candid_EntityType_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6);
            return from_candid_Activity_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async logRecruiterMetrics(arg0: string, arg1: string, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: bigint, arg7: bigint, arg8: string): Promise<RecruiterMetrics> {
        if (this.processError) {
            try {
                const result = await this.actor.logRecruiterMetrics(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logRecruiterMetrics(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async logVendorMetrics(arg0: string, arg1: string, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: number, arg7: number): Promise<VendorMetrics> {
        if (this.processError) {
            try {
                const result = await this.actor.logVendorMetrics(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logVendorMetrics(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async matchBench(arg0: string): Promise<Array<BenchMatch>> {
        if (this.processError) {
            try {
                const result = await this.actor.matchBench(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.matchBench(arg0);
            return result;
        }
    }
    async matchResumeToJobs(arg0: string): Promise<Array<ResumeJobMatch>> {
        if (this.processError) {
            try {
                const result = await this.actor.matchResumeToJobs(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.matchResumeToJobs(arg0);
            return result;
        }
    }
    async rejectItem(arg0: string, arg1: string, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectItem(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectItem(arg0, arg1, arg2);
            return result;
        }
    }
    async runFollowUpEngine(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.runFollowUpEngine();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.runFollowUpEngine();
            return result;
        }
    }
    async seedSampleData(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.seedSampleData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedSampleData();
            return result;
        }
    }
    async snoozeItem(arg0: string, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.snoozeItem(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.snoozeItem(arg0, arg1);
            return result;
        }
    }
    async updateApprovalItem(arg0: ApprovalItem): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateApprovalItem(to_candid_ApprovalItem_n52(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateApprovalItem(to_candid_ApprovalItem_n52(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateCandidate(arg0: Candidate): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCandidate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCandidate(arg0);
            return result;
        }
    }
    async updateClient(arg0: Client): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateClient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateClient(arg0);
            return result;
        }
    }
    async updateEntityStage(arg0: string, arg1: EntityType, arg2: string, arg3: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "requiresApproval";
        requiresApproval: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEntityStage(arg0, to_candid_EntityType_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return from_candid_variant_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEntityStage(arg0, to_candid_EntityType_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return from_candid_variant_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateFollowUpStatus(arg0: string, arg1: string, arg2: string | null, arg3: bigint | null): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFollowUpStatus(arg0, arg1, to_candid_opt_n47(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n55(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFollowUpStatus(arg0, arg1, to_candid_opt_n47(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n55(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async updateJob(arg0: Job): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateJob(to_candid_Job_n56(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateJob(to_candid_Job_n56(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateRecruiter(arg0: Recruiter): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRecruiter(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRecruiter(arg0);
            return result;
        }
    }
    async updateResume(arg0: string, arg1: ResumeInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateResume(arg0, to_candid_ResumeInput_n13(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateResume(arg0, to_candid_ResumeInput_n13(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateSubmission(arg0: Submission): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSubmission(to_candid_Submission_n58(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSubmission(to_candid_Submission_n58(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateSubmissionStage(arg0: string, arg1: string, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSubmissionStage(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSubmissionStage(arg0, arg1, arg2);
            return result;
        }
    }
    async updateVendor(arg0: Vendor): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVendor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVendor(arg0);
            return result;
        }
    }
    async uploadBenchRecords(arg0: Array<BenchRecordInput>): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadBenchRecords(arg0);
                return from_candid_variant_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadBenchRecords(arg0);
            return from_candid_variant_n60(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Activity_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Activity): Activity {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_ApprovalItem_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalItem): ApprovalItem {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_EntityType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EntityType): EntityType {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_FollowUp_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FollowUp): FollowUp {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_HealthStatus_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HealthStatus): HealthStatus {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_Job_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Job): Job {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_PipelineStage_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PipelineStage): PipelineStage {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_PulseDashboard_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PulseDashboard): PulseDashboard {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_PulseRow_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PulseRow): PulseRow {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_Resume_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Resume): Resume {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Submission_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Submission): Submission {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_EntityId]): EntityId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Candidate]): Candidate | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Client]): Client | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Job]): Job | null {
    return value.length === 0 ? null : from_candid_Job_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Recruiter]): Recruiter | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RecruiterMetrics]): RecruiterMetrics | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Resume]): Resume | null {
    return value.length === 0 ? null : from_candid_Resume_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Submission]): Submission | null {
    return value.length === 0 ? null : from_candid_Submission_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Vendor]): Vendor | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VendorMetrics]): VendorMetrics | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _EntityId;
    status: string;
    triggerReason: string;
    approvedAt: [] | [_Timestamp];
    approvedBy: [] | [string];
    createdAt: _Timestamp;
    suggestedAction: string;
    sentAt: [] | [_Timestamp];
    entityId: _EntityId;
    snoozedUntil: [] | [_Timestamp];
    entityType: _EntityType;
    suggestedMessage: string;
}): {
    id: EntityId;
    status: string;
    triggerReason: string;
    approvedAt?: Timestamp;
    approvedBy?: string;
    createdAt: Timestamp;
    suggestedAction: string;
    sentAt?: Timestamp;
    entityId: EntityId;
    snoozedUntil?: Timestamp;
    entityType: EntityType;
    suggestedMessage: string;
} {
    return {
        id: value.id,
        status: value.status,
        triggerReason: value.triggerReason,
        approvedAt: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.approvedAt)),
        approvedBy: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.approvedBy)),
        createdAt: value.createdAt,
        suggestedAction: value.suggestedAction,
        sentAt: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.sentAt)),
        entityId: value.entityId,
        snoozedUntil: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.snoozedUntil)),
        entityType: from_candid_EntityType_n7(_uploadFile, _downloadFile, value.entityType),
        suggestedMessage: value.suggestedMessage
    };
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _EntityId;
    status: string;
    title: string;
    clientId: _EntityId;
    createdAt: _Timestamp;
    rateMax: number;
    rateMin: number;
    filledAt: [] | [_Timestamp];
    requirements: string;
}): {
    id: EntityId;
    status: string;
    title: string;
    clientId: EntityId;
    createdAt: Timestamp;
    rateMax: number;
    rateMin: number;
    filledAt?: Timestamp;
    requirements: string;
} {
    return {
        id: value.id,
        status: value.status,
        title: value.title,
        clientId: value.clientId,
        createdAt: value.createdAt,
        rateMax: value.rateMax,
        rateMin: value.rateMin,
        filledAt: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.filledAt)),
        requirements: value.requirements
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _EntityId;
    rawText: string;
    sourceVendorId: [] | [_EntityId];
    yearsExperience: [] | [bigint];
    createdAt: _Timestamp;
    fileName: string;
    extractedRole: string;
    email: [] | [string];
    extractedSkills: Array<string>;
    extractedExperience: string;
    candidateName: string;
    phone: [] | [string];
    location: [] | [string];
    fileUrl: string;
}): {
    id: EntityId;
    rawText: string;
    sourceVendorId?: EntityId;
    yearsExperience?: bigint;
    createdAt: Timestamp;
    fileName: string;
    extractedRole: string;
    email?: string;
    extractedSkills: Array<string>;
    extractedExperience: string;
    candidateName: string;
    phone?: string;
    location?: string;
    fileUrl: string;
} {
    return {
        id: value.id,
        rawText: value.rawText,
        sourceVendorId: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.sourceVendorId)),
        yearsExperience: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.yearsExperience)),
        createdAt: value.createdAt,
        fileName: value.fileName,
        extractedRole: value.extractedRole,
        email: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.email)),
        extractedSkills: value.extractedSkills,
        extractedExperience: value.extractedExperience,
        candidateName: value.candidateName,
        phone: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.phone)),
        location: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.location)),
        fileUrl: value.fileUrl
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _EntityId;
    rateProposed: number;
    pipelineHistory: Array<_PipelineHistoryEntry>;
    approvedAt: [] | [_Timestamp];
    approvedBy: [] | [string];
    jobId: _EntityId;
    submittedAt: _Timestamp;
    submittedBy: string;
    resumeId: [] | [_EntityId];
    pipelineStage: _SubmissionPipelineStage;
    vendorId: [] | [_EntityId];
    notes: [] | [string];
    candidateId: _EntityId;
}): {
    id: EntityId;
    rateProposed: number;
    pipelineHistory: Array<PipelineHistoryEntry>;
    approvedAt?: Timestamp;
    approvedBy?: string;
    jobId: EntityId;
    submittedAt: Timestamp;
    submittedBy: string;
    resumeId?: EntityId;
    pipelineStage: SubmissionPipelineStage;
    vendorId?: EntityId;
    notes?: string;
    candidateId: EntityId;
} {
    return {
        id: value.id,
        rateProposed: value.rateProposed,
        pipelineHistory: value.pipelineHistory,
        approvedAt: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.approvedAt)),
        approvedBy: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.approvedBy)),
        jobId: value.jobId,
        submittedAt: value.submittedAt,
        submittedBy: value.submittedBy,
        resumeId: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.resumeId)),
        pipelineStage: value.pipelineStage,
        vendorId: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.vendorId)),
        notes: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.notes)),
        candidateId: value.candidateId
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _EntityId;
    direction: string;
    activityType: string;
    approvedAt: [] | [_Timestamp];
    approvedBy: [] | [string];
    createdAt: _Timestamp;
    createdBy: string;
    entityId: _EntityId;
    notes: string;
    requiresApproval: boolean;
    entityType: _EntityType;
}): {
    id: EntityId;
    direction: string;
    activityType: string;
    approvedAt?: Timestamp;
    approvedBy?: string;
    createdAt: Timestamp;
    createdBy: string;
    entityId: EntityId;
    notes: string;
    requiresApproval: boolean;
    entityType: EntityType;
} {
    return {
        id: value.id,
        direction: value.direction,
        activityType: value.activityType,
        approvedAt: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.approvedAt)),
        approvedBy: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.approvedBy)),
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        entityId: value.entityId,
        notes: value.notes,
        requiresApproval: value.requiresApproval,
        entityType: from_candid_EntityType_n7(_uploadFile, _downloadFile, value.entityType)
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    stageOrder: bigint;
    requiresApproval: boolean;
    entityType: _EntityType;
    slaHours: bigint;
    stageName: string;
}): {
    stageOrder: bigint;
    requiresApproval: boolean;
    entityType: EntityType;
    slaHours: bigint;
    stageName: string;
} {
    return {
        stageOrder: value.stageOrder,
        requiresApproval: value.requiresApproval,
        entityType: from_candid_EntityType_n7(_uploadFile, _downloadFile, value.entityType),
        slaHours: value.slaHours,
        stageName: value.stageName
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    generatedAt: _Timestamp;
    rows: Array<_PulseRow>;
}): {
    generatedAt: Timestamp;
    rows: Array<PulseRow>;
} {
    return {
        generatedAt: value.generatedAt,
        rows: from_candid_vec_n35(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    healthStatus: _HealthStatus;
    pipelineStage: string;
    entityId: _EntityId;
    actionNeeded: string;
    entityName: string;
    entityType: _EntityType;
    healthScore: bigint;
    lastActivityAt: _Timestamp;
}): {
    healthStatus: HealthStatus;
    pipelineStage: string;
    entityId: EntityId;
    actionNeeded: string;
    entityName: string;
    entityType: EntityType;
    healthScore: bigint;
    lastActivityAt: Timestamp;
} {
    return {
        healthStatus: from_candid_HealthStatus_n38(_uploadFile, _downloadFile, value.healthStatus),
        pipelineStage: value.pipelineStage,
        entityId: value.entityId,
        actionNeeded: value.actionNeeded,
        entityName: value.entityName,
        entityType: from_candid_EntityType_n7(_uploadFile, _downloadFile, value.entityType),
        healthScore: value.healthScore,
        lastActivityAt: value.lastActivityAt
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _EntityId;
    status: string;
    approvedAt: [] | [_Timestamp];
    approvedBy: [] | [string];
    description: string;
    entityId: _EntityId;
    snoozedUntil: [] | [_Timestamp];
    notes: [] | [string];
    itemType: string;
    details: string;
    entityName: string;
    entityType: _EntityType;
    requestedAt: _Timestamp;
    requestedBy: string;
}): {
    id: EntityId;
    status: string;
    approvedAt?: Timestamp;
    approvedBy?: string;
    description: string;
    entityId: EntityId;
    snoozedUntil?: Timestamp;
    notes?: string;
    itemType: string;
    details: string;
    entityName: string;
    entityType: EntityType;
    requestedAt: Timestamp;
    requestedBy: string;
} {
    return {
        id: value.id,
        status: value.status,
        approvedAt: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.approvedAt)),
        approvedBy: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.approvedBy)),
        description: value.description,
        entityId: value.entityId,
        snoozedUntil: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.snoozedUntil)),
        notes: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.notes)),
        itemType: value.itemType,
        details: value.details,
        entityName: value.entityName,
        entityType: from_candid_EntityType_n7(_uploadFile, _downloadFile, value.entityType),
        requestedAt: value.requestedAt,
        requestedBy: value.requestedBy
    };
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: boolean;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: boolean;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    red: null;
} | {
    green: null;
} | {
    yellow: null;
}): HealthStatus {
    return "red" in value ? HealthStatus.red : "green" in value ? HealthStatus.green : "yellow" in value ? HealthStatus.yellow : value;
}
function from_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    requiresApproval: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "requiresApproval";
    requiresApproval: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "requiresApproval" in value ? {
        __kind__: "requiresApproval",
        requiresApproval: value.requiresApproval
    } : value;
}
function from_candid_variant_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: bigint;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    client: null;
} | {
    vendor: null;
} | {
    recruiter: null;
} | {
    candidate: null;
}): EntityType {
    return "client" in value ? EntityType.client : "vendor" in value ? EntityType.vendor : "recruiter" in value ? EntityType.recruiter : "candidate" in value ? EntityType.candidate : value;
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Activity>): Array<Activity> {
    return value.map((x)=>from_candid_Activity_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PipelineStage>): Array<PipelineStage> {
    return value.map((x)=>from_candid_PipelineStage_n31(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PulseRow>): Array<PulseRow> {
    return value.map((x)=>from_candid_PulseRow_n36(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ApprovalItem>): Array<ApprovalItem> {
    return value.map((x)=>from_candid_ApprovalItem_n3(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FollowUp>): Array<FollowUp> {
    return value.map((x)=>from_candid_FollowUp_n9(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Job>): Array<Job> {
    return value.map((x)=>from_candid_Job_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Resume>): Array<Resume> {
    return value.map((x)=>from_candid_Resume_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Submission>): Array<Submission> {
    return value.map((x)=>from_candid_Submission_n21(_uploadFile, _downloadFile, x));
}
function to_candid_ApprovalItem_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalItem): _ApprovalItem {
    return to_candid_record_n53(_uploadFile, _downloadFile, value);
}
function to_candid_EntityType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EntityType): _EntityType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Job_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Job): _Job {
    return to_candid_record_n57(_uploadFile, _downloadFile, value);
}
function to_candid_ResumeInput_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ResumeInput): _ResumeInput {
    return to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_SubmissionInput_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubmissionInput): _SubmissionInput {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_Submission_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Submission): _Submission {
    return to_candid_record_n59(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    rawText: string;
    sourceVendorId?: EntityId;
    yearsExperience?: bigint;
    fileName: string;
    extractedRole: string;
    email?: string;
    extractedSkills: Array<string>;
    extractedExperience: string;
    candidateName: string;
    phone?: string;
    location?: string;
    fileUrl: string;
}): {
    rawText: string;
    sourceVendorId: [] | [_EntityId];
    yearsExperience: [] | [bigint];
    fileName: string;
    extractedRole: string;
    email: [] | [string];
    extractedSkills: Array<string>;
    extractedExperience: string;
    candidateName: string;
    phone: [] | [string];
    location: [] | [string];
    fileUrl: string;
} {
    return {
        rawText: value.rawText,
        sourceVendorId: value.sourceVendorId ? candid_some(value.sourceVendorId) : candid_none(),
        yearsExperience: value.yearsExperience ? candid_some(value.yearsExperience) : candid_none(),
        fileName: value.fileName,
        extractedRole: value.extractedRole,
        email: value.email ? candid_some(value.email) : candid_none(),
        extractedSkills: value.extractedSkills,
        extractedExperience: value.extractedExperience,
        candidateName: value.candidateName,
        phone: value.phone ? candid_some(value.phone) : candid_none(),
        location: value.location ? candid_some(value.location) : candid_none(),
        fileUrl: value.fileUrl
    };
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    rateProposed: number;
    jobId: EntityId;
    submittedBy: string;
    resumeId?: EntityId;
    vendorId?: EntityId;
    notes?: string;
    candidateId: EntityId;
}): {
    rateProposed: number;
    jobId: _EntityId;
    submittedBy: string;
    resumeId: [] | [_EntityId];
    vendorId: [] | [_EntityId];
    notes: [] | [string];
    candidateId: _EntityId;
} {
    return {
        rateProposed: value.rateProposed,
        jobId: value.jobId,
        submittedBy: value.submittedBy,
        resumeId: value.resumeId ? candid_some(value.resumeId) : candid_none(),
        vendorId: value.vendorId ? candid_some(value.vendorId) : candid_none(),
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        candidateId: value.candidateId
    };
}
function to_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: EntityId;
    status: string;
    approvedAt?: Timestamp;
    approvedBy?: string;
    description: string;
    entityId: EntityId;
    snoozedUntil?: Timestamp;
    notes?: string;
    itemType: string;
    details: string;
    entityName: string;
    entityType: EntityType;
    requestedAt: Timestamp;
    requestedBy: string;
}): {
    id: _EntityId;
    status: string;
    approvedAt: [] | [_Timestamp];
    approvedBy: [] | [string];
    description: string;
    entityId: _EntityId;
    snoozedUntil: [] | [_Timestamp];
    notes: [] | [string];
    itemType: string;
    details: string;
    entityName: string;
    entityType: _EntityType;
    requestedAt: _Timestamp;
    requestedBy: string;
} {
    return {
        id: value.id,
        status: value.status,
        approvedAt: value.approvedAt ? candid_some(value.approvedAt) : candid_none(),
        approvedBy: value.approvedBy ? candid_some(value.approvedBy) : candid_none(),
        description: value.description,
        entityId: value.entityId,
        snoozedUntil: value.snoozedUntil ? candid_some(value.snoozedUntil) : candid_none(),
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        itemType: value.itemType,
        details: value.details,
        entityName: value.entityName,
        entityType: to_candid_EntityType_n1(_uploadFile, _downloadFile, value.entityType),
        requestedAt: value.requestedAt,
        requestedBy: value.requestedBy
    };
}
function to_candid_record_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: EntityId;
    status: string;
    title: string;
    clientId: EntityId;
    createdAt: Timestamp;
    rateMax: number;
    rateMin: number;
    filledAt?: Timestamp;
    requirements: string;
}): {
    id: _EntityId;
    status: string;
    title: string;
    clientId: _EntityId;
    createdAt: _Timestamp;
    rateMax: number;
    rateMin: number;
    filledAt: [] | [_Timestamp];
    requirements: string;
} {
    return {
        id: value.id,
        status: value.status,
        title: value.title,
        clientId: value.clientId,
        createdAt: value.createdAt,
        rateMax: value.rateMax,
        rateMin: value.rateMin,
        filledAt: value.filledAt ? candid_some(value.filledAt) : candid_none(),
        requirements: value.requirements
    };
}
function to_candid_record_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: EntityId;
    rateProposed: number;
    pipelineHistory: Array<PipelineHistoryEntry>;
    approvedAt?: Timestamp;
    approvedBy?: string;
    jobId: EntityId;
    submittedAt: Timestamp;
    submittedBy: string;
    resumeId?: EntityId;
    pipelineStage: SubmissionPipelineStage;
    vendorId?: EntityId;
    notes?: string;
    candidateId: EntityId;
}): {
    id: _EntityId;
    rateProposed: number;
    pipelineHistory: Array<_PipelineHistoryEntry>;
    approvedAt: [] | [_Timestamp];
    approvedBy: [] | [string];
    jobId: _EntityId;
    submittedAt: _Timestamp;
    submittedBy: string;
    resumeId: [] | [_EntityId];
    pipelineStage: _SubmissionPipelineStage;
    vendorId: [] | [_EntityId];
    notes: [] | [string];
    candidateId: _EntityId;
} {
    return {
        id: value.id,
        rateProposed: value.rateProposed,
        pipelineHistory: value.pipelineHistory,
        approvedAt: value.approvedAt ? candid_some(value.approvedAt) : candid_none(),
        approvedBy: value.approvedBy ? candid_some(value.approvedBy) : candid_none(),
        jobId: value.jobId,
        submittedAt: value.submittedAt,
        submittedBy: value.submittedBy,
        resumeId: value.resumeId ? candid_some(value.resumeId) : candid_none(),
        pipelineStage: value.pipelineStage,
        vendorId: value.vendorId ? candid_some(value.vendorId) : candid_none(),
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        candidateId: value.candidateId
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EntityType): {
    client: null;
} | {
    vendor: null;
} | {
    recruiter: null;
} | {
    candidate: null;
} {
    return value == EntityType.client ? {
        client: null
    } : value == EntityType.vendor ? {
        vendor: null
    } : value == EntityType.recruiter ? {
        recruiter: null
    } : value == EntityType.candidate ? {
        candidate: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
